name: Build App

on:
    push:
        branches: [ "main" ]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              run: npm run buildDev
      
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                commit-message: "Build App"
                branch: build
                delete-branch: true
                sign-commits: true
                title: Create App
                body: |
                    # Changes
                    Built app
                maintainer-can-modify: true