name: Build App

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Begin installation
              run: |
                cd src
                npm i
                cd publicSrc
                npm i

            - name: Build
              run: |
                cd src
                npm run buildDev
            
            - uses: actions/setup-node@v4
              with:
                node-version: 20
      
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                delete-branch: true